### ISSUE TITLE
Neo Coolcam Curtain Switch instruction manual

### ISSUE THREAD

**Issue by dwgreven** [mruiter/com.neo#115] opened 2019-10-02 15:34 UTC
Hey Marco,

Hereby the instruction manual for the Neo CoolCam Curtain Switch. I think you need it for the codes in the manual?

Thanks in advance,
Wilfred
[NEO_CC_Curtain_sw.pdf](https://github.com/mruiter/com.neo/files/3681913/NEO_CC_Curtain_sw.pdf)

**Comment by dwgreven** [comment] 2019-10-31 13:26
Hey Marco,
Hereby the id’s i think you need for the curtain swidge.

Thanks in advance,
Wilfred
![0DA6569F-F45D-4842-AB86-49B73E206107](https://user-images.githubusercontent.com/52658446/67950596-30bb2180-fbea-11e9-9405-bce703fb9e02.png)

**Comment by mruiter** [comment] 2019-10-31 14:04
Did they supply a manual with the setting ids with the device ? Would be nice if you could post some photos of those 2

Verstuurd vanaf mijn iPhone

**Comment by dwgreven** [comment] 2019-10-31 14:09
The manual is a pdf in my first message: NEO_CC_Curtain_sw.pdf

**Comment by SamBlooming** [comment] 2019-11-17 20:17
Hi Marco
I’m eagerly waiting for the functionality for the curtain switch device. By any chance, do you need any help? E.g. documentation, testing...? Let me know.
Cheers

**Comment by dwgreven** [comment] 2019-11-26 12:07
Hi Marco,
Do you need anymore? 
I am also eagerly waiting for the functionality for the curtain switch device.
Thanks in advance,
Wilfred

**Comment by mruiter** [comment] 2019-12-04 14:38
I put some support code for the controller in the v2.1.1 app thats on my github.
Its a shot in the dark since i dont have the device and the documentation isnt that clear on how its implemented .

Please let me know if it does anything :)

You need to sideload the app from my github with athom cli since this version isnt in the appstore yet

**Comment by dwgreven** [comment] 2019-12-04 19:00
Hi Sam,
I hope you are able to test? I have tried, but not succesfull with cli, nodejs etc.
Greetings,
Wilfred

**Comment by SamBlooming** [comment] 2019-12-04 20:25
Hi Marco
I managed to include the curtain device. That went smoothly.
 The slider however is not updated when i click on the up/down button. These clicks seem not to change anything in the app.
On a less important note, i notice that i can not change the “controler led ...” booleans to false in the advanced menu.

**Comment by SamBlooming** [comment] 2019-12-04 20:28
Let me know if i need to check a specific behavior.

**Comment by SamBlooming** [comment] 2019-12-04 20:30
By the way, is it expected behavior that after installing v2.1.1 (from v2.0.19) the double switches of neo coolcam are no longer recognized (i.e. need to be re-included?)

**Comment by mruiter** [comment] 2019-12-05 04:00
Yes it’s in the changelog . It’s now using the proper naming convention Neo has switched 2
A repair is mentioned in the changelog as needed for the wall switches on V2.1 series of the app

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment] 2019-12-05 07:36
Version with debug on is on my GitHub 

Athom app run is the command to run this version in temp memory as debug with output on the console box

Verstuurd vanaf mijn iPhone

**Comment by SamBlooming** [comment] 2019-12-06 07:18
Hi Marco,

I managed to run the latest app from Github on my Homey.

actions:
- removed curtain controller device
- run the latest app from github on my Homey
- installed my curtain controller device again. Device ID = 70;
- pressed a few times on the buttons; up, down and center. But nothing was logged in cmd window during these actions! 
- I have copy/pasted the whole command window as of running the app in the attachment.

[LOG.txt](https://github.com/mruiter/com.neo/files/3930843/LOG.txt)

**Comment by mruiter** [comment] 2019-12-06 08:01
Strange , it should output some more info on the console. Are you sure you have my latest uploaded version from github where i enabled debugging on the CC ?

And when you add it . Does it get added as the Curtain Controller with a picture with up down en pause button on the icon ? Or is it added as a generic device ? 
If its still a generic devices then there is something wrong with the device id's i added

**Comment by SamBlooming** [comment] 2019-12-06 08:23
Hi Marco
The icon is a curtain switch with up/down and center button.
I downloaded it from github yesterday around 5pm ; unzipped it; went to the unzipped folder in node.js cmd; and logged into homey and RUN the app. That should be the right approach right?

**Comment by mruiter** [comment] 2019-12-06 09:02
That should be it indeed . Strange . When a button is pushed the zwave command / output it generates should show up in the console 

Verstuurd vanaf mijn iPhone

**Comment by SamBlooming** [comment] 2019-12-06 09:19
Should this also be generated for coolcam PIR’s and door sensors which are activated? Then i could check at least if the absence of the output is device specific or generic. In the latter case the issue should be at my side i guess.

**Comment by mruiter** [comment] 2019-12-06 09:53
Maybee you can also give me the outcome of the zwave lig straight from homey

You can find that on developer.athom.com under tools zwave 

On the bottom there is log . You can enable it and filter it on the device I’d the CC has
Maybee that gives some more info on what it’s trying to deliver 2 homey

Verstuurd vanaf mijn iPhone

**Comment by SamBlooming** [comment] 2019-12-06 13:00
Ok. Will do my best to do this in the weekend, but not sure if I succeed. 
By the way, is your CC already anywhere near?

**Comment by mruiter** [comment] 2019-12-06 13:13
It’s still somewhere in limbo between China and NL

Verstuurd vanaf mijn iPhone

**Comment by SamBlooming** [comment] 2019-12-06 19:15
aiii.... it still has to pass the customs (which turns out to be the bottle neck for my devices).

**Comment by SamBlooming** [comment] 2019-12-06 19:20
Hi Marco,
I did do the things you requested. I downloaded the app from Github again just to be sure I am using the latest greatest. I used the device on homey to change the curtain position a few times, then I clicked a few times on the buttons on the CC (up and down). As you can see, these actions are not logged in the cmd window. However, Homey does detect some actions (I filtered for the CC device id).
I hope the attached log files can help you somehow. Cheers,

[log_nodeJS.txt](https://github.com/mruiter/com.neo/files/3933661/log_nodeJS.txt)
[log_homey.txt](https://github.com/mruiter/com.neo/files/3933662/log_homey.txt)

**Comment by SamBlooming** [comment] 2019-12-06 19:25
> Hi Sam,
> I hope you are able to test? I have tried, but not succesfull with cli, nodejs etc.
> Greetings,
> Wilfred

Hi Wilfred,
As you can see I did manage to get a few steps further but no logging yet. In case you want to give it another try and see if logging works for you here are 2 useful links which helped me to work with nodejs:
1. https://www.youtube.com/watch?v=JnjAyWKSEIE&feature=youtu.be
2. https://community.athom.com/t/how-to-cli-install-method/198/5

**Comment by SamBlooming** [comment] 2019-12-07 06:29
Hi Marco
Odds are that the logging is missing because I havent calibrated my CC yet. The manual mentions that many (if not all) commands are ignored if there is no calibration.
My CC is also not wired to any curtain or roller shutter. It is simply on life and neutral wires only and will need to be used as associated with a qubino controller which is completely wired...
Perhaps i will be more successful if i manage to associate it properly (new to me so may take some time) and then calibrate the CC.

**Comment by dwgreven** [comment] 2019-12-07 20:54
Hi Marco and Sam,
I am little bit further. I have included the CC and now it is useable from homey: i can with homey open and close the roller shutter.
But the buttons on the CC don’t work anymore, so opening and closing by hand is not possible yet.
Greetings,
Wilfred

**Comment by mruiter** [comment] 2019-12-08 05:02
You can try in settings to change setting 5 as you can see in the picture I attached . Maybee it didn’t get set right because this seems to disable the buttons



Verstuurd vanaf mijn iPhone

**Comment by dwgreven** [comment] 2019-12-08 07:51
Hi Marco,

Because i saw no picture, i did a change in the settings, but it gave an error. In “waarde” i changed the field in 5,1,1; to set the buttons on. The error is in red.



Greetings,
Wilfred

**Comment by dwgreven** [comment] 2019-12-08 11:13
![AA4F3BF3-F555-4298-977A-830433FEBBE1](https://user-images.githubusercontent.com/52658446/70388559-e7fa4380-19b3-11ea-9dd4-5b25df396078.png)
The picture with the error, not in comment before attached.
Wilfred

**Comment by mruiter** [comment] 2019-12-09 13:48
I added setting 5 in the app.
Latest version is on github. But i'm not sure if it needs to be true/1 for them to be enabled or false.
Since te setting name is Button Switch Function Disable - and the manual tells that a true is working buttons and i would expect it to be false when i look at the name so hope you can give it a try

**Comment by dwgreven** [comment] 2019-12-09 16:37
Hi Marco,
I have tested v2.1.2. It is working as intended. The buttons are now working and it is working in a flow or “by hand” in homey.
The only strange thing i noticed is:
- the field “knopbediening uitschakelen” set to no and save is not enough 
- in the field “waarde” set “5,1,1;” and save and the buttons are working.

Later on i clear the field “waarde” and save, but the buttons are still working.
I paste a picture with the settings “apparaat specifiek” i use for now.
Let me know if i have to test something else.
Sam is it for you working also?
Greetings, Wilfred
![45995CE6-FBF2-4981-8A53-C677E7B649FB](https://user-images.githubusercontent.com/52658446/70454163-443f8f00-1aaa-11ea-8842-fb34b832ed92.png)

**Comment by mruiter** [comment] 2019-12-11 09:05
Yes the manual has a error on that setting. I corrected this in V2.1.3 

Will close this issue then and hope you enjoy youre controller :) 

Thx for the help in testing

**Closed by mruiter** 2019-12-11 09:05 UTC

**Comment by SamBlooming** [comment] 2019-12-11 20:47
Hi guys,
One last update from my side;
I am using v2.1.2 and it seems to work as intended. I did have to manual calibrate the CC to get things work properly.
- i can send commands via the app and the cc reacts on it accordingly.
- i can press a button on the cc and it is received by homey properly.
In my case, homey triggers a scene after pressing a button and that works.

I havent succeeded turning off the default LED light when the switch is disabled (perhaps already solved in 2.1.3).

Thanks for your efforts Marco! I will definitely enjoy this new device.

Cheers

**Comment by 2azure** [comment] 2020-06-09 08:19
Hi, the app is working great. Although I have one request. Would it be possible to adjust the device button to be ON or OFF when curtains or fully up or down. Now it is always in the ON mode. 
Changing this value it would make it possible to apply flows to it. 

If you want, I can grant you access to my homey, or send you a test device.

Thanks, and keep up the great work you are doing!

Cor
