### ISSUE TITLE
Power Wallplug stopped reporting Power Consumption

### ISSUE THREAD

**Issue by ma-be** [mruiter/com.neo#78] opened 2019-01-21 07:24 UTC
Hi,
few days ago I moved the wallplug to another room. Since then there is no Power and Current reading. The Voltage is ok.

Yesterday I installed a brand new one and there is the same problem :-(.

I have tried disconnecting the wallplugs, restoring the factory settings, restarting the app, restarting homey... Still the same.

Do you have any suggestion what to do?
Thanks,
M. 

PS: Homey v2.0.0, app v2.0.14

**Comment by pkroeze** [comment] 2019-01-21 12:32
The power meter reports a negative number. Have a deviceID 512 eu version

![homey negative number](https://user-images.githubusercontent.com/5010813/51474850-da7aa180-1d80-11e9-898f-df5f4e467a85.png)

**Comment by mruiter** [comment] 2019-01-21 12:36
What happens when you set reset the power with the power meter reset ? 

Verstuurd vanaf mijn iPhone

**Comment by pkroeze** [comment] 2019-01-21 15:14
Just the same after the reset, is just starts counting from: -2147483648, the minimal of an integer. from +0,08 to -21474836,40. see the graphic below.

![image](https://user-images.githubusercontent.com/5010813/51482598-28020900-1d97-11e9-924a-2b2841d7e4ef.png)

**Comment by ma-be** [comment] 2019-01-21 16:08
Sorry for these basic questions...
How can I reset the power with the power meter reset?
Where can I find the deviceID?

**Comment by ma-be** [comment] 2019-01-21 16:19
My situation:
device: Power Wallplug, EU version
driver: NAS-WR01ZE
device ID: 3 (product type ID)

after power meter reset (via Flow action):
![image](https://user-images.githubusercontent.com/11045804/51486347-bdee6180-1da0-11e9-91ff-3521388ad121.png)

**Comment by mruiter** [comment] 2019-01-21 16:30
Just to be sure .. this is only with the new I’d plugs ? If not then there is another new issue in homey core 

Verstuurd vanaf mijn iPhone

**Comment by ma-be** [comment] 2019-01-21 16:40
Both wallplugs of mine are the old device ID (i.e. Product Type ID = 3). Power and Current readings are 0.

pkroeze's wallplugs are the new device ID (i.e. Product Type ID = 512). Power readings are negative.

**Comment by pkroeze** [comment] 2019-01-21 17:18
Have 2 powerplugs from coolcam;

- Have one type 512 with the problem.
- Have one type 3 without any problems.

**Comment by pkroeze** [comment] 2019-01-22 11:02
The re-dding of the device didn't work. in the attachement the readings of the last 6 hours eported from Homey: [NeoCoolcam 512.zip.zip](https://github.com/mruiter/com.neo/files/2782441/NeoCoolcam.512.zip.zip)

Perhaps it is a faulty device.

**Comment by mruiter** [comment] 2019-01-23 07:17
Doesnt seem to be failty pkroeze. It seems its new hardware, basics are the same so switching works but next to the new ID the led now supports different colors and reports back different.
I will order the new version plug so i can do more testing myself.

Do you have a link of the reseller you bought it from. Then im sure im getting the same.

**Comment by mruiter** [comment] 2019-01-23 07:47
Thx ordered:)

Verstuurd vanaf mijn iPhone

**Comment by ma-be** [comment] 2019-01-27 18:50
Well, I have discovered the really interesting source of my problem :-).
The missing Power readings happen only with energy effecient LED lights (I guess consumption less then 4W). Power readings for more hungry devices are reported.

This however raises the question how accurate are those readings.
Would it be possible that this kind of error is caused by the software (app) or is this only an issue caused by hardware?

**Comment by mruiter** [comment] 2019-01-27 19:04
This is normal behaviors and also noted in the manual . You need at least 4 or 5 watts before power reports start .


Verstuurd vanaf mijn iPhone

**Comment by ma-be** [comment] 2019-01-27 19:38
Thank you.
... and I am sorry, that I have not noticed this behavior in the manual.

**Comment by mruiter** [comment] 2019-02-12 13:41
I'm trying to find the problem with the - values . Seems like a bug in the firmware of the plugs :(

**Comment by Phil872** [comment] 2019-03-14 09:39
Ich habe dasselbe Problem. Schon mehrere Plugs der Reihe 512 ausprobiert und immer wieder das gleiche. Habe einen TV, AV Receiver usw. dranhängen, Verbrauch ca. 500W und 2A. Am Anfang funktioniert alles problemlos und nach ca. 1,5 Stunden zeigt es mir die Minuswerte an. Zurücksetzen hat nichts geholfen da sich der Wert nicht mehr löschen lässt.

**Comment by Phil872** [comment] 2019-03-16 09:39
Kleines Update: hab gestern einen neuen Wall Plug der Reihe 512 erhalten und zwischen TV, AV Receiver... geschlossen. Siehe da, der Wall Plug misst komischerweise den Energieverbrauch ohne das er Minuswerte anzeigt. Wieso? Ich weiß es nicht. Bin mittlerweile ratlos...

**Comment by Xibel** [comment] 2019-05-01 12:44
Any progress on the negative meter_power issue? I have 4 of these new power plugs and all of them report negatives.

**Comment by newatschoen** [comment] 2019-05-22 06:31
same here... negative value in power meter

**Comment by Phil872** [comment] 2019-05-22 07:18
Das komische an der Sache ist, dass es bei dem Wall Plug an meinem Fernseher nur noch hin und wieder Minuswerte anzeigt. Von dauerhaften Minuswerten zu einer fast beständigen Anzeige des Energieverbrauchs ohne das ich irgendwas verändert habe. Ich verstehe absolut nicht wieso...

**Comment by mruiter** [comment] 2019-05-22 08:33
Neo still hasn’t fixed the firmware bug. It does not have anything to do with homey . It’s the plug itself reporting back these strange values

Verstuurd vanaf mijn iPhone

**Comment by Xibel** [comment] 2019-05-22 09:19
I have send a mail to the Neo producer but until now no response. Maybe some of you can also send a mail to ask for support. The website of the producer: https://szneo.com/en/contact/index.php
I send the mail to support@szneo.com and neo_support@hotmail.com. (Hotmail??? yea they use hotmail).

My e-mail:

Dear Lee / support,

I bought 18 Neo Z-Wave Smart Power Plug from banggood.com. These are the Product Type ID 512. These are the new types probably since januari 2019. All of these power plugs have an energy reporting issue. Most of the time the total energy used meter in KWh is reporting a negative number like -21474835.86. Sometimes it reports a positive number but you need to be lucky to see this. Product Type ID 3 does not have this problem.

Some of these power plugs also hang themselves suddenly at a random moment. In that case I am not able to use the little knob on the power plug. The LED is burning but there is no power transmitted to the connected device. I need to unplug the Power Plug and replug it in to continue operation.

I am using a Athom Homey as a Z-wave controller witch have both 300 and 500 Z-Wave chips.

In the following screenshot you can find information about how my Homey controller is reporting one of the device:

<screenshot>

In this picture you can see negative value how it is shown in the app:

<screenshot>

And a piece of logfile where you van see that the value is indeed negative being send from the Power Plug:

[2019-05-17T11:15:38.091Z] Node[4]: [COMMAND_CLASS_METER] {"Properties1 (Raw)":{"type":"Buffer","data":[33]},"Properties1":{"Scale bit 2":false,"Meter Type":"Electric meter","Rate Type":"Import","Meter Type (Parsed)":{"value":"Electric meter"},"Rate Type (Parsed)":{"value":"Import"}},"Properties2 (Raw)":{"type":"Buffer","data":[68]},"Properties2":{"Size":4,"Scale bits 10":0,"Precision":2},"Meter Value":{"type":"Buffer","data":[128,0,0,62]},"Delta Time (Raw)":{"type":"Buffer","data":[1,25]},"Delta Time":281,"Previous Meter Value":{"type":"Buffer","data":[128,0,0]},"Scale 2 (Raw)":{"type":"Buffer","data":[62]},"Scale 2":62,"Meter Value (Parsed)":-21474835.86}

I have hardreset a few of the Power Plugs and reconnected them to the Z-Wave controller but the energy consumption value remains
negative.

Are you aware of this problem and is there a way to repair this problem? Can I somehow update firmware on these 18 plug’s?

I have contacted Banggood but they keep me asking stupid questions about my Z-Wave controller gateway. They are stalling me in the process and that is why I am contacting you directly.

Please contact me with all information you know about these Product Typ 512 Power Plug’s.

With kind regards,

<name>

**Comment by ma-be** [comment] 2019-05-22 09:56
@Xibel: just for the record, I can confirm all the behaviour you are describing regarding the Product Type 512 (even the random hang up when only the un/replugging them helps).

@mruiter: as I have both Product Types (3 & 512), I have noticed following differences:
- Type 3 never connects as Secure device
- Type 512 always connects as Secure device
- Type 512 has only 2 association groups in the Advanced settings, though according to the product manual, there should be 3 association groups (Type 3 does have those 3 groups)
These differences probably do not have any relation to the negative energy consumption value, but what about the hang up problem?

**Comment by mruiter** [comment] 2019-05-22 10:29
Yes one is secure and the other is not . By design .

Driver split will be done in the future then the newer one will get 3 ass groups 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment] 2019-12-06 08:09
There are multiple issues being reported in this ticket.

There is a new version in my github and pending appstore approval that should fix reporting in , settings and some other errors.

The setting changes came to light by a user that got a new manual with its plugs (not the faulty old one that just had the V1 text copied )

Also this users doesnt report the negative values on the plug so it also seems neo has resolved its firmware bug ... I will close this issue since theres also another one with the negative value. Please be sure to check out the new v.2.1 series that should arrive soon in the appstore

**Closed by mruiter** 2019-12-06 08:09 UTC
